/** Selected transparent layers from Ultimate-HOI4-GFX (credits: src/assets/hoi4/CREDITS.txt). */
export const HOI4_PIECES = {
  study: new URL('../assets/hoi4/pieces/Book Open.png', import.meta.url).href,
  authority: new URL('../assets/hoi4/pieces/Capitol.png', import.meta.url).href,
  revolt: new URL('../assets/hoi4/pieces/Fist Colored.png', import.meta.url).href,
  security: new URL('../assets/hoi4/pieces/Shield Forward.png', import.meta.url).href,
  alliance: new URL('../assets/hoi4/pieces/Hands Shaking.png', import.meta.url).href,
  assembly: new URL('../assets/hoi4/pieces/Ballot.png', import.meta.url).href,
  industry: new URL('../assets/hoi4/pieces/Factories.png', import.meta.url).href,
  media: new URL('../assets/hoi4/pieces/Megaphone.png', import.meta.url).href,
  culture: new URL('../assets/hoi4/pieces/Brush.png', import.meta.url).href,
  reform: new URL('../assets/hoi4/pieces/Circular Arrows.png', import.meta.url).href,
  law: new URL('../assets/hoi4/pieces/Scales Golden.png', import.meta.url).href,
  research: new URL('../assets/hoi4/pieces/Computer.png', import.meta.url).href,
  economy: new URL('../assets/hoi4/pieces/Cash Fan.png', import.meta.url).href,
  command: new URL('../assets/hoi4/pieces/Soldier Saluting.png', import.meta.url).href,
  crisis: new URL('../assets/hoi4/pieces/Clock.png', import.meta.url).href,
  campus: new URL('../assets/hoi4/pieces/Building.png', import.meta.url).href,
  paper: new URL('../assets/hoi4/pieces/Paper.png', import.meta.url).href,
  writing: new URL('../assets/hoi4/pieces/Hand Writing.png', import.meta.url).href,
  marx: new URL('../assets/hoi4/pieces/Karl Marx.png', import.meta.url).href,
  banner: new URL('../assets/hoi4/pieces/Banner.png', import.meta.url).href,
  fire: new URL('../assets/hoi4/pieces/Fire.png', import.meta.url).href,
  redStar: new URL('../assets/hoi4/pieces/Star Red.png', import.meta.url).href,
  rifle: new URL('../assets/hoi4/pieces/Rifle.png', import.meta.url).href,
  coalition: new URL('../assets/hoi4/pieces/Hands Shaking2.png', import.meta.url).href,
  release: new URL('../assets/hoi4/pieces/Handcuffs Broken.png', import.meta.url).href,
  map: new URL('../assets/hoi4/pieces/Map with Knife.png', import.meta.url).href,
  padlock: new URL('../assets/hoi4/pieces/Padlock.png', import.meta.url).href,
  book: new URL('../assets/hoi4/pieces/Book.png', import.meta.url).href,
  spy: new URL('../assets/hoi4/pieces/Spy.png', import.meta.url).href,
  parliament: new URL('../assets/hoi4/pieces/Parliament.png', import.meta.url).href,
  bunker: new URL('../assets/hoi4/pieces/Bunker.png', import.meta.url).href,
  guillotine: new URL('../assets/hoi4/pieces/Guillotine.png', import.meta.url).href,
  deficit: new URL('../assets/hoi4/pieces/Cash Flow Negative.png', import.meta.url).href,
  rose: new URL('../assets/hoi4/pieces/Rose.png', import.meta.url).href,
  blueprint: new URL('../assets/hoi4/pieces/Blueprints.png', import.meta.url).href,
  train: new URL('../assets/hoi4/pieces/Train.png', import.meta.url).href,
  bear: new URL('../assets/hoi4/pieces/Bear.png', import.meta.url).href,
  classified: new URL('../assets/hoi4/pieces/Documents Classified.png', import.meta.url).href,
} as const;

export type Hoi4Piece = keyof typeof HOI4_PIECES;

export const SPIRIT_BACKGROUNDS = {
  neutral: new URL('../assets/hoi4/spirit-backgrounds/Rectangle.png', import.meta.url).href,
  negative: new URL('../assets/hoi4/spirit-backgrounds/Rectangle 2.png', import.meta.url).href,
  positive: new URL('../assets/hoi4/spirit-backgrounds/Shield Blue.png', import.meta.url).href,
} as const;

export const SPIRIT_BACKGROUND_VARIANTS: Record<string, string> = {
  Army: new URL('../assets/hoi4/spirit-backgrounds/Army.png', import.meta.url).href,
  Bars: new URL('../assets/hoi4/spirit-backgrounds/Bars.png', import.meta.url).href,
  Circle: new URL('../assets/hoi4/spirit-backgrounds/Circle.png', import.meta.url).href,
  Diamonds: new URL('../assets/hoi4/spirit-backgrounds/Diamonds.png', import.meta.url).href,
  Fire: new URL('../assets/hoi4/spirit-backgrounds/Fire.png', import.meta.url).href,
  Intrigue: new URL('../assets/hoi4/spirit-backgrounds/Intrigue.png', import.meta.url).href,
  Losange: new URL('../assets/hoi4/spirit-backgrounds/Losange.png', import.meta.url).href,
  'Military Police': new URL('../assets/hoi4/spirit-backgrounds/Military Police.png', import.meta.url).href,
  Pentagon: new URL('../assets/hoi4/spirit-backgrounds/Pentagon.png', import.meta.url).href,
  Polygon: new URL('../assets/hoi4/spirit-backgrounds/Polygon.png', import.meta.url).href,
  Rectangle: new URL('../assets/hoi4/spirit-backgrounds/Rectangle.png', import.meta.url).href,
  Ring: new URL('../assets/hoi4/spirit-backgrounds/Ring.png', import.meta.url).href,
  Rows: new URL('../assets/hoi4/spirit-backgrounds/Rows.png', import.meta.url).href,
  Shield: new URL('../assets/hoi4/spirit-backgrounds/Shield.png', import.meta.url).href,
  Sun: new URL('../assets/hoi4/spirit-backgrounds/Sun.png', import.meta.url).href,
  Upgrade: new URL('../assets/hoi4/spirit-backgrounds/Upgrade.png', import.meta.url).href,
};

export const FOCUS_PIECE_OVERRIDES: Record<string, Hoi4Piece> = {
  build_art: 'blueprint', fake_five_edu: 'paper', ban_books: 'book',
  dorm_talks: 'spy', contact_pan: 'coalition', read_marx: 'marx',
  rally_classes: 'banner', protest_privilege: 'revolt', charge_b3: 'fire',
  steel_toad: 'bear', democratic_councils: 'parliament',
  establish_vanguard: 'redStar', student_militia: 'rifle',
  broad_coalition: 'coalition', convene_assembly: 'parliament',
  authoritarian_exit_negotiation: 'release', post_negotiation_events: 'classified',
  wu_patrol: 'spy', wu_martial_law: 'padlock', wu_inspection: 'classified',
  wu_resume_classes: 'book', gx_anarchy_map_start: 'map',
  jidi_establish_committee: 'parliament', perfect_hengshui: 'paper',
  despair_street_fight: 'rifle', wu_armed_guard: 'rifle',
  underground_print: 'paper', write_papers: 'writing',
  bill_transparent_finances: 'economy', jidi_teacher_contracts: 'deficit',
  gx_campus_rewrite: 'writing', ultimate_master_teacher: 'book',
  purge_moderates: 'guillotine', wu_teacher_relief: 'alliance',
};

export const SPIRIT_PIECE_OVERRIDES: Record<string, Hoi4Piece> = {
  exam_pressure: 'paper', b3_fortress: 'bunker',
  wu_patrol_spirit: 'spy', democratic_councils_spirit: 'parliament',
  assembly_dynamics: 'assembly',
  red_toad_politburo: 'redStar', jidi_corporate_utopia_spirit: 'economy',
  jidi_riot_spirit: 'fire', wu_martial_law_spirit: 'padlock',
  strict_discipline_spirit: 'padlock', red_culture_spirit: 'rose',
  extra_mock_exams_spirit: 'paper', club_freedom_spirit: 'rose',
  no_evening_study_spirit: 'book', student_welfare_spirit: 'alliance',
  transparent_finances_spirit: 'economy', curriculum_reform_spirit: 'reform',
  wu_rule_of_law_spirit: 'law', wu_armed_guard_spirit: 'rifle',
  wu_iron_curtain_spirit: 'bunker',
};
