/** Generated by scripts/build_loading_art.py; every art/载入图 image is bundled. */
export const LOADING_ART: Record<string, string> = {
  "B3革命": new URL("../assets/loading/B3革命.webp", import.meta.url).href,
  "内卷": new URL("../assets/loading/内卷.webp", import.meta.url).href,
  "军训": new URL("../assets/loading/军训.webp", import.meta.url).href,
  "及第之梦": new URL("../assets/loading/及第之梦.webp", import.meta.url).href,
  "合一之春": new URL("../assets/loading/合一之春.webp", import.meta.url).href,
  "合一之春2": new URL("../assets/loading/合一之春2.webp", import.meta.url).href,
  "合一文革": new URL("../assets/loading/合一文革.webp", import.meta.url).href,
  "合一文革2": new URL("../assets/loading/合一文革2.webp", import.meta.url).href,
  "合一陨落": new URL("../assets/loading/合一陨落.webp", import.meta.url).href,
  "封安保时代": new URL("../assets/loading/封安保时代.webp", import.meta.url).href,
  "批斗": new URL("../assets/loading/批斗.webp", import.meta.url).href,
  "校园涂鸦1": new URL("../assets/loading/校园涂鸦1.webp", import.meta.url).href,
  "校园涂鸦2": new URL("../assets/loading/校园涂鸦2.webp", import.meta.url).href,
  "清场": new URL("../assets/loading/清场.webp", import.meta.url).href,
  "特级": new URL("../assets/loading/特级.webp", import.meta.url).href,
  "特级0": new URL("../assets/loading/特级0.webp", import.meta.url).href,
  "特级教师": new URL("../assets/loading/特级教师.webp", import.meta.url).href,
  "红色风暴": new URL("../assets/loading/红色风暴.webp", import.meta.url).href,
  "行政楼": new URL("../assets/loading/行政楼.webp", import.meta.url).href,
  "裤熊逢春": new URL("../assets/loading/裤熊逢春.webp", import.meta.url).href,
  "陈栋": new URL("../assets/loading/陈栋.webp", import.meta.url).href,
  "陈栋与合一": new URL("../assets/loading/陈栋与合一.webp", import.meta.url).href,
};

export const LOADING_ART_URLS = Object.values(LOADING_ART);
