"""Build lightweight game copies of every source image in art/载入图.

The source artwork is never modified. Run from the repository root.
"""

from pathlib import Path
import json
from PIL import Image, ImageOps


source = Path('art/载入图')
output = Path('src/assets/loading')
output.mkdir(parents=True, exist_ok=True)

for image_path in sorted(source.glob('*.png')):
    with Image.open(image_path) as image:
        image = ImageOps.exif_transpose(image).convert('RGB')
        image.thumbnail((1920, 1200), Image.Resampling.LANCZOS)
        destination = output / f'{image_path.stem}.webp'
        image.save(destination, 'WEBP', quality=84, method=6)
        print(f'{image_path.name} -> {destination.name} ({image.width}x{image.height}, {destination.stat().st_size // 1024} KiB)')

catalog = Path('src/config/loadingArtwork.ts')
entries = [f"  {json.dumps(path.stem, ensure_ascii=False)}: new URL({json.dumps('../assets/loading/' + path.name, ensure_ascii=False)}, import.meta.url).href,"
           for path in sorted(output.glob('*.webp'))]
catalog.write_text('\n'.join([
    '/** Generated by scripts/build_loading_art.py; every art/载入图 image is bundled. */',
    'export const LOADING_ART: Record<string, string> = {',
    *entries,
    '};',
    '',
    'export const LOADING_ART_URLS = Object.values(LOADING_ART);',
    '',
]), encoding='utf-8')

logo_source = Path('art/美术素材')
logo_output = Path('src/assets/ui')
logo_output.mkdir(parents=True, exist_ok=True)
for source_name, target_name in [('TNO：合一风云LOGO.png', 'game-logo.webp'), ('xfp-logo (2).png', 'studio-logo.webp')]:
    with Image.open(logo_source / source_name) as image:
        image = ImageOps.exif_transpose(image).convert('RGBA')
        image.thumbnail((1200, 1200), Image.Resampling.LANCZOS)
        image.save(logo_output / target_name, 'WEBP', quality=88, method=6)
        print(f'{source_name} -> {target_name} ({(logo_output / target_name).stat().st_size // 1024} KiB)')
